---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gees-docker.artifactory.platform.manulife.io/buildtools-base

inputs:
- name: benchmarkauto

outputs:
- name: target


run:
  path: benchmarkauto/concourse/scripts/ping-val-ilb.sh
